In [1]:
import numpy as np

## Numpy Data types and attributes

In [3]:
a_1 = np.array([1, 2, 3])
a_1

array([1, 2, 3])

In [9]:
a_2 = np.array([[1.0, 2.5, 3], [4, 5.7, 6.9]])
a_2

array([[1. , 2.5, 3. ],
       [4. , 5.7, 6.9]])

In [5]:
a_3 = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a_1.shape

(3,)

In [10]:
a_2.shape

(2, 3)

In [11]:
a_3.shape

(2, 3, 3)

In [12]:
import pandas as pd

In [15]:
df = pd.DataFrame(a_2)
df

0    1    2
0  1.0  2.5  3.0
1  4.0  5.7  6.9

In [26]:
type(a_1), type(a_2), type(a_3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [21]:
a_1.ndim, a_2.ndim, a_3.ndim

(1, 2, 3)

In [23]:
a_1.dtype, a_2.dtype, a_3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [25]:
a_1.size, a_2.size, a_3.size

(3, 6, 18)

In [29]:
## This checks for the length of the arrays and it doesn't consider size of the array (3D or 2D)
len(a_1), len(a_2), len(a_3)

(3, 2, 2)