In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

In [9]:
a2 = np.array([[1, 2.5, 3],
               [4, 5.5, 6]])

In [5]:
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]],
               [[10, 11, 12], 
               [13, 14, 15], 
               [16, 17, 18]]])

In [6]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [10]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [11]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [12]:
import pandas as pd
df_2 = pd.DataFrame(a2)
df_2

0    1    2
0  1.0  2.5  3.0
1  4.0  5.5  6.0

In [13]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
## range_array = np.arange(0, 100, 3) || range_array = np.arange(100, step = 3)
range_array = np.arange(0, 100, step = 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
random_1 = np.random.randint(10, size=(7, 2))
random_1

array([[5, 6],
       [8, 4],
       [1, 3],
       [1, 4],
       [0, 6],
       [5, 3],
       [8, 9]])

In [20]:
random_2 = np.random.random((3, 5))
random_2

array([[0.73917306, 0.8486152 , 0.42400019, 0.49072859, 0.34776162],
       [0.5296725 , 0.85098292, 0.314208  , 0.09224724, 0.12096804],
       [0.32753408, 0.84606697, 0.40481152, 0.6933085 , 0.56378939]])

In [22]:
np.random.seed(42)
random_3 = np.random.randint(10, size = (4, 6))
random_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [23]:
random_3[0]

array([6, 3, 7, 4, 6, 9])

In [25]:
random_3[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [26]:
random_3.shape

(4, 6)

In [27]:
random_3[:2, :2]

array([[6, 3],
       [2, 6]])

In [29]:
np.random.seed(0)
random_4 = np.random.randint(10, size=(3, 5))
ones_2 = np.ones((3, 5))
random_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [30]:
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
random_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [33]:
random_4 + ones_2

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [34]:
ones_3 = np.ones((5, 3))

In [36]:
random_4 + ones_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

The above cell couldn't run because the arrays had different dimensions and none of them had a 1 in their dimensions 
I can fix it by reshaping the array or transposing it.

In [39]:
ones_4 = ones_3.reshape((3, 5))
ones_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
random_4 + ones_4

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [38]:
random_4 - ones_2

array([[ 4., -1.,  2.,  2.,  6.],
       [ 8.,  2.,  4.,  1.,  3.],
       [ 6.,  5.,  7.,  7.,  0.]])

In [41]:
random_4 * ones_2

array([[5., 0., 3., 3., 7.],
       [9., 3., 5., 2., 4.],
       [7., 6., 8., 8., 1.]])

In [43]:
random_4 ** 2

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [44]:
np.square(random_4)

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [45]:
np.mean(random_4)

4.733333333333333

In [46]:
np.max(random_4)

9

In [47]:
np.min(random_4)

0

In [48]:
np.std(random_4)

2.6449112566503166

In [49]:
np.var(random_4)

6.995555555555556

In [50]:
random_5 = random_4.reshape(3, 5, 1)
random_5

array([[[5],
        [0],
        [3],
        [3],
        [7]],

       [[9],
        [3],
        [5],
        [2],
        [4]],

       [[7],
        [6],
        [8],
        [8],
        [1]]])

In [51]:
## Transpose inverts the dimensions of an array
random_4.T

array([[5, 9, 7],
       [0, 3, 6],
       [3, 5, 8],
       [3, 2, 8],
       [7, 4, 1]])

In [52]:
random_4.shape, random_4.T.shape

((3, 5), (5, 3))

In [53]:
np.random.seed(0)
random_6 = np.random.randint(10, size = (3,3))
random_7 = np.random.randint(10, size = (3, 2))

In [54]:
np.dot(random_6, random_7)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [55]:
np.random.seed(0)
random_8 = np.random.randint(10, size = (4, 3))
random_9 = np.random.randint(10, size = (4, 3))

In [56]:
np.dot(random_8, random_9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [57]:
## Dot product works when inner dimensions are equal and hence it couldn't work on this one
## Most common way to fix this is to use a transpose on one of the arrays.
np.dot(random_8, random_9.T)

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

In [58]:
random_8 > random_9

array([[False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [59]:
random_8 >= random_9

array([[False, False,  True],
       [False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [60]:
bool_arr = random_8 > 7
bool_arr

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [61]:
random_8

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [62]:
random_8 == random_9

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [63]:
np.sort(random_8)

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [64]:
np.argsort(random_8)

array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [65]:
np.argmax(random_8)

5

In [66]:
np.argmin(random_8)

1

In [67]:
np.argmax(random_8, axis=1)

array([0, 2, 1, 1], dtype=int64)

In [68]:
random_8

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [69]:
np.argmin(random_8, axis=0)

array([1, 0, 2], dtype=int64)

In [73]:
norm_dist = np.arange(10, step = 1)

In [74]:
norm_dist

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
even_dist = np.arange(1, 100, 10)

In [76]:
even_dist

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])